include ../../../rules.mk

chvatal_graphs=chvatal.gexf\
               chvatal.gml\
               chvatal.graphml\
               chvatal.gv\
               chvatal.net

all: $(chvatal_graphs)

OPTIONS=--name chvatal

clean:
	rm -f $(chvatal_graphs)
