include ../../../rules.mk

desargues_graphs=desargues.gexf\
                 desargues.gml\
                 desargues.graphml\
                 desargues.gv\
                 desargues.net

all: $(desargues_graphs)

OPTIONS=--name desargues

clean:
	rm -f $(desargues_graphs)
