include ../../../rules.mk

dodecahedral_graphs=dodecahedral.gexf\
                    dodecahedral.gml\
                    dodecahedral.graphml\
                    dodecahedral.gv\
                    dodecahedral.net

all: $(dodecahedral_graphs)

OPTIONS=--name dodecahedral

clean:
	rm -f $(dodecahedral_graphs)
