include ../../../rules.mk

octahedral_graphs=octahedral.gexf\
                  octahedral.gml\
                  octahedral.graphml\
                  octahedral.net

all: $(octahedral_graphs)

OPTIONS=--name octahedral

clean:
	rm -f $(octahedral_graphs)
