include ../../../rules.mk

frucht_graphs=frucht.gexf\
              frucht.gml\
              frucht.graphml\
              frucht.net

all: $(frucht_graphs)

OPTIONS=--name frucht

clean:
	rm -f $(frucht_graphs)
