include ../../../rules.mk

heawood_graphs=heawood.gexf\
               heawood.gml\
               heawood.graphml\
               heawood.gv\
               heawood.net

all: $(heawood_graphs)

OPTIONS=--name heawood

clean:
	rm -f $(heawood_graphs)
