include ../../../rules.mk

tetrahedral_graphs=tetrahedral.gexf\
                   tetrahedral.gml\
                   tetrahedral.graphml\
                   tetrahedral.net

all: $(tetrahedral_graphs)

OPTIONS=--name tetrahedral

clean:
	rm -f $(tetrahedral_graphs)
