include ../../../rules.mk

tutte_graphs=tutte.gexf\
             tutte.gml\
             tutte.graphml\
             tutte.gv\
             tutte.net

all: $(tutte_graphs)

OPTIONS=--name tutte

clean:
	rm -f $(tutte_graphs)
