include ../../../rules.mk

pappus_graphs=pappus.gexf\
              pappus.gml\
              pappus.graphml\
              pappus.gv\
              pappus.net

all: $(pappus_graphs)

OPTIONS=--name pappus

clean:
	rm -f $(pappus_graphs)
