include ../../../rules.mk

bull_graphs=bull.gexf\
            bull.gml\
            bull.graphml\
            bull.gv\
            bull.net

all: $(bull_graphs)

OPTIONS=--name bull

clean:
	rm -f $(bull_graphs)
