include ../../../rules.mk

petersen_graphs=petersen.gexf\
                petersen.gml\
                petersen.graphml\
                petersen.gv\
                petersen.net

all: $(petersen_graphs)

OPTIONS=--name petersen

clean:
	rm -f $(petersen_graphs)
