include ../../../rules.mk

icosahedral_graphs=icosahedral.gexf\
                   icosahedral.gml\
                   icosahedral.graphml\
                   icosahedral.net

all: $(icosahedral_graphs)

OPTIONS=--name icosahedral

clean:
	rm -f $(icosahedral_graphs)
